# For .properties
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/<schema_name>
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update

# For .yml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "root"
    url: jdbc:mysql://localhost:3306/users
    username: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 2525
