cloud:
  aws:
    credentials:
      access-key: AKIA4YYTIQXIG2OCJTPY
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: spring-boot-practice
