# Port number and context path
server.port=8080
server.servlet.context-path=/${context_path}


# Profile to be used to connect to Database
#spring.profiles.active=mysql
spring.profiles.active=postgres

# Kafka logging config
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR