# Driver to be used to connect to Database
spring.datasource.driver-class-name=org.postgresql.Driver

# Database connection URL
spring.datasource.url=jdbc:postgresql://${db_host}:5432/${db_default_database}

# Credentials to connect to Database
spring.datasource.username=${db_user_name}
spring.datasource.password=${db_password}

# Configuring to update the Database structure if required
# spring.jpa.hibernate.ddl-auto=update
